export class CreateViajeCommand {
  constructor(
    public readonly fk_usuario: number,
    public readonly fk_manifiesto: number,
    public readonly fk_cliente: number,
    public readonly fk_origen: number,
    public readonly fk_destino: number,
    public readonly codigo: string,
    public readonly observaciones: string,
    public readonly estado_viaje: boolean,
    public readonly producto: string,
    public readonly detalle_producto: string,
    public readonly direccion_llegada: string,
    public readonly fecha_salida: Date,
    public readonly fecha_llegada: Date,
    public readonly latitud_origen: number,
    public readonly longitud_origen: number,
    public readonly latitud_destino: number,
    public readonly longitud_destino: number,
    public readonly fecha_hora_salida: Date,
    public readonly fecha_hora_llegada: Date,
    public readonly horas_pactadas_cargue: number,
    public readonly horas_pactadas_descargue: number,
    public readonly exoneracion_legal: string,
  ) { }
}
