export class CreateNewViajeCommand {
  constructor(
    // viaje
    public readonly fk_usuario: number,
    public readonly fk_cliente: number,
    public readonly fk_origen: number,
    public readonly fk_destino: number,
    public readonly codigo: string,
    public readonly observaciones: string,
    public readonly producto: string,
    public readonly detalle_producto: string,
    public readonly direccion_llegada: string,
    public readonly fecha_salida: Date,
    public readonly fecha_llegada: Date,
    public readonly latitud_origen: number,
    public readonly longitud_origen: number,
    public readonly latitud_destino: number,
    public readonly longitud_destino: number,
    public readonly hora_salida: Date,
    public readonly hora_llegada: Date,
    public readonly horas_pactadas_cargue: number,
    public readonly horas_pactadas_descargue: number,
    public readonly exoneracion_legal: string,
    // Manifiesto
    public readonly fk_vehiculo: number,
    public readonly flete_total: number,
    public readonly porcentaje_retencion_fuente: number,
    public readonly valor_retencion_fuente: number,
    public readonly porcentaje_ica: number,
    public readonly valor_ica: number,
    public readonly deduccion_fiscal: number,
    public readonly neto_a_pagar: number,
    public readonly anticipo: number,
    public readonly saldo_a_pagar: number,
    public readonly total_gastos: number,
    public readonly queda_al_carro: number,
    public readonly a_favor_del_carro: number,
    public readonly porcentaje_conductor: number,
    public readonly ganancia_conductor: number,
    // Remesa
    public readonly numero_remesa: string,
    public readonly numero_autorizacion: string,
    public readonly tipo_empaque: string,
    public readonly naturaleza_carga: string,
    public readonly codigo_armonizado: string,
    public readonly cantidad: number,
    public readonly unidad_medida: string,
    public readonly peso_total: number,
    public readonly mercancia_peligrosa: boolean,
    public readonly observaciones_remesa: string,
    // Mercancía peligrosa (opcionales)
    public readonly codigo_un?: string,
    public readonly grupo_riesgo?: string,
    public readonly caracteristica_peligrosidad?: string,
    public readonly embalaje_envase?: string,
  ) { }
}
