create table cliente (
  id_cliente int generated by default as identity primary key,
  fk_usuario int,
  nit varchar,
  nombre_cliente varchar(50),
  telefono varchar(13)
);

create table gasto (
  id_gasto int generated by default as identity primary key,
  nombre_gasto varchar(100)
);

create table lugar (
  id_lugar int generated by default as identity primary key,
  nombre_lugar varchar(50)
);

create table manifiesto (
  id_manifiesto int generated by default as identity primary key,
  flete_total decimal(15,5),
  porcentaje_retencion_fuente decimal(9,4),
  valor_retencion_fuente decimal(15,5),
  porcentaje_ica decimal(9,4),
  valor_ica decimal(15,5),
  deduccion_fiscal decimal(15,5),
  neto_a_pagar decimal(15,5),
  anticipo decimal(15,5),
  saldo_a_pagar decimal(15,5),
  total_gastos decimal(15,5),
  queda_al_carro decimal(15,5),
  a_favor_del_carro decimal(15,5),
  porcentaje_conductor decimal(9,4),
  ganancia_conductor decimal(15,5)
);

create table rol (
  id_rol int generated by default as identity primary key,
  nombre_rol varchar(20)
);

create table tipodoc (
  id_tipodoc int generated by default as identity primary key,
  nombre_documento varchar(50),
  abreviatura varchar(15)
);

create table usuario (
  id_usuario int generated by default as identity primary key,
  fk_tipodoc int,
  num_doc varchar unique,
  fk_rol int,
  fk_contador int,
  p_nombre varchar(20),
  s_nombre varchar(20),
  p_apellido varchar(20),
  s_apellido varchar(20),
  telefono varchar(13),
  correo varchar(300) unique,
  contrasena text,
  estado_usuario boolean default true
);

create table viaje (
  id_viaje int generated by default as identity primary key,
  fk_usuario int,
  fk_manifiesto int,
  fk_cliente int,
  fk_origen int,
  fk_destino int,
  codigo varchar unique,
  observaciones varchar(250),
  estado_viaje boolean,
  producto varchar(250),
  detalle_producto varchar(250),
  direccion_llegada varchar(250),
  fecha_salida date,
  fecha_llegada date
);

create table gastosxviaje (
  id_gastoxviaje int generated by default as identity primary key,
  fk_viaje int,
  fk_gasto int,
  valor decimal(15,5),
  detalles varchar(250)
);

create table chat (
  id_chat int generated by default as identity primary key,
  fk_usuario int,
  nombre_chat varchar(100),
  fecha_creacion timestamp default current_timestamp
);

create table mensajes (
  id_mensaje int generated by default as identity primary key,
  fk_chat int,
  pregunta text,
  respuesta text,
  fecha timestamp default current_timestamp
);

alter table cliente add foreign key (fk_usuario) references usuario(id_usuario) on delete cascade;

alter table usuario add foreign key (fk_rol) references rol (id_rol) on delete restrict;

alter table usuario add foreign key (fk_contador) references usuario (id_usuario) on delete set null;

alter table usuario add foreign key (fk_tipodoc) references tipodoc (id_tipodoc) on delete restrict;

alter table viaje add foreign key (fk_usuario) references usuario (id_usuario) on delete cascade;

alter table viaje add foreign key (fk_manifiesto) references manifiesto (id_manifiesto) on delete set null;

alter table viaje add foreign key (fk_cliente) references cliente (id_cliente) on delete set null;

alter table viaje add foreign key (fk_origen) references lugar (id_lugar) on delete set null;

alter table viaje add foreign key (fk_destino) references lugar (id_lugar) on delete set null;

alter table gastosxviaje add foreign key (fk_viaje) references viaje (id_viaje) on delete cascade;

alter table gastosxviaje add foreign key (fk_gasto) references gasto (id_gasto) on delete restrict;

alter table chat add foreign key (fk_usuario) references usuario (id_usuario) on delete cascade;

alter table mensajes add foreign key (fk_chat) references chat (id_chat) on delete cascade;

INSERT INTO gasto (nombre_gasto) VALUES
('Combustible'),
('Peaje'),
('Mantenimiento'),
('Llantas'),
('Lavado'),
('Otro'),
('Cargue'),
('Descargue');

INSERT INTO rol (nombre_rol) VALUES
('Conductor'),
('Contador'),
('Administrador');

INSERT INTO tipodoc (nombre_documento, abreviatura) VALUES
('Registro civil', 'RC'),
('Tarjeta de identidad', 'TI'),
('Cédula de ciudadanía', 'CC'),
('Tarjeta de extranjería', 'TE'),
('Cédula de extranjería', 'CE'),
('Número de identificación tributaria', 'NIT'),
('Pasaporte', 'PP'),
('Permiso especial de permanencia', 'PEP'),
('Documento de identificación extranjero', 'DIE'),
('NUIP', 'NUIP'),
('NIT de otro país', 'FOREIGN_NIT');

INSERT INTO lugar (nombre_lugar) VALUES
('Bogotá D.C.'),
('Medellín'),
('Cali'),
('Barranquilla'),
('Cartagena'),
('Cúcuta'),
('Bucaramanga'),
('Pereira'),
('Santa Marta'),
('Ibagué'),
('Manizales'),
('Neiva'),
('Villavicencio'),
('Armenia'),
('Pasto');
