CREATE TABLE "cliente" (
  "id_cliente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nit" varchar,
  "cliente" varchar(50),
  "telefono" varchar(13)
);

CREATE TABLE "gasto" (
  "id_gasto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gasto" varchar(100)
);

CREATE TABLE "lugar" (
  "id_lugar" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_lugar" varchar(50)
);

CREATE TABLE "manifiesto" (
  "id_manifiesto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "flete_total" decimal(15,5),
  "porcentaje_retencion_fuente" decimal(9,4),
  "valor_retencion_fuente" decimal(15,5),
  "porcentaje_ica" decimal(9,4),
  "valor_ica" decimal(15,5),
  "deduccion_fiscal" decimal(15,5),
  "neto_a_pagar" decimal(15,5),
  "anticipo" decimal(15,5),
  "saldo_a_pagar" decimal(15,5),
  "total_gastos" decimal(15,5),
  "queda_al_carro" decimal(15,5),
  "a_favor_del_carro" decimal(15,5),
  "porcentaje_conductor" decimal(9,4),
  "ganacia_conductor" decimal(15,5)
);

CREATE TABLE "perfil" (
  "id_perfil" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "perfil" varchar(9)
);

CREATE TABLE "tipodoc" (
  "id_tipodoc" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "documento" varchar(50),
  "abreviatura" varchar(15)
);

CREATE TABLE "usuario" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fk_tipodoc" varchar(2),
  "num_doc" varchar,
  "fk_perfil" int,
  "fk_contador" int,
  "p_nombre" varchar(20),
  "s_nombre" varchar(20),
  "p_apellido" varchar(20),
  "s_apellido" varchar(20),
  "telefono" varchar(13),
  "correo" varchar(300),
  "contrasena" varchar(50)
);

CREATE TABLE "viaje" (
  "id_viaje" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fk_usuario" int,
  "fk_manifiesto" int,
  "fk_cliente" int,
  "fk_origen" int,
  "fk_destino" int,
  "codigo" varchar,
  "observaciones" varchar(250),
  "estado" boolean,
  "producto" varchar(250),
  "detalle_prod" varchar(250),
  "direccion_llegada" varchar(250),
  "f_salida" date,
  "f_llegada" date
);

CREATE TABLE "gastosxviaje" (
  "id_gastoxviaje" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fk_viaje" int,
  "fk_gasto" int,
  "valor" decimal(15,5),
  "detalles" varchar(250)
);

CREATE TABLE "chat" (
  "id_chat" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fk_usuario" int,
  "nombre_chat" varchar(100),
  "fecha_creacion" timestamp
);

CREATE TABLE "mensajes" (
  "id_mensaje" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fk_chat" int,
  "pregunta" text,
  "respuesta" text,
  "fecha" timestamp
);

ALTER TABLE "usuario" ADD FOREIGN KEY ("fk_perfil") REFERENCES "perfil" ("id_perfil");

ALTER TABLE "usuario" ADD FOREIGN KEY ("fk_contador") REFERENCES "perfil" ("id_perfil");

ALTER TABLE "usuario" ADD FOREIGN KEY ("fk_tipodoc") REFERENCES "tipodoc" ("id_tipodoc");

ALTER TABLE "viaje" ADD FOREIGN KEY ("fk_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "viaje" ADD FOREIGN KEY ("fk_manifiesto") REFERENCES "manifiesto" ("id_manifiesto");

ALTER TABLE "viaje" ADD FOREIGN KEY ("fk_cliente") REFERENCES "cliente" ("id_cliente");

ALTER TABLE "viaje" ADD FOREIGN KEY ("fk_origen") REFERENCES "lugar" ("id_lugar");

ALTER TABLE "viaje" ADD FOREIGN KEY ("fk_destino") REFERENCES "lugar" ("id_lugar");

ALTER TABLE "gastosxviaje" ADD FOREIGN KEY ("fk_viaje") REFERENCES "viaje" ("id_viaje");

ALTER TABLE "gastosxviaje" ADD FOREIGN KEY ("fk_gasto") REFERENCES "gasto" ("id_gasto");

ALTER TABLE "chat" ADD FOREIGN KEY ("fk_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "mensajes" ADD FOREIGN KEY ("fk_chat") REFERENCES "chat" ("id_chat");
